# runs on 3.10 

name: Python application test with Github Actions <> GCP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.11
    - name: Install Conda 
      run: make conda_setup
    - name: Install dependencies
      run: |
        make install-gcp 
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Cleanup 
      run: |
        make clean 
    
    
